GET http://localhost:4000/users/

###
GET http://localhost:4000/users/15

###


###
POST http://localhost:4000/users/
Content-Type: application/json

{
    "email": "charan@nxtwave.co.in",
    "password": "charan123",
    "role": "mentor",
    "first_name": "charan",
    "last_name": "kumar",
    "phone_number": "9876543210",
    "profile_picture": null,
    "is_active": true,
    "last_login": null
}

###

POST http://localhost:4000/auth/login
Content-Type: application/json

{
    "email": "charan@nxtwave.co.in",
    "password": "charan123"
}

###
GET http://localhost:4000/doubts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE1LCJlbWFpbCI6ImNoYXJhbkBueHR3YXZlLmNvLmluIiwicm9sZSI6Im1lbnRvciIsImlhdCI6MTc0OTg5NzQ0NiwiZXhwIjoxNzUwMDcwMjQ2fQ.Zc68XT-rZSL5JUx6hHUaUnkOfos2RIcZ_W3qZXeO6fY

###
POST http://localhost:4000/doubts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE1LCJlbWFpbCI6ImNoYXJhbkBueHR3YXZlLmNvLmluIiwicm9sZSI6Im1lbnRvciIsImlhdCI6MTc0OTg5NzQ0NiwiZXhwIjoxNzUwMDcwMjQ2fQ.Zc68XT-rZSL5JUx6hHUaUnkOfos2RIcZ_W3qZXeO6fY
Content-Type: application/json

{
    "description": "I am facing difficulty in understanding the concept of inheritance in Java",
    "section_id": 1,
    "subject_id": 3,
    "resolution_status": "Unresolved"
}

###
DELETE http://localhost:4000/doubts/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE1LCJlbWFpbCI6ImNoYXJhbkBueHR3YXZlLmNvLmluIiwicm9sZSI6Im1lbnRvciIsImlhdCI6MTc0OTg5NzQ0NiwiZXhwIjoxNzUwMDcwMjQ2fQ.Zc68XT-rZSL5JUx6hHUaUnkOfos2RIcZ_W3qZXeO6fY

###
GET http://localhost:4000/options/sections
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE1LCJlbWFpbCI6ImNoYXJhbkBueHR3YXZlLmNvLmluIiwicm9sZSI6Im1lbnRvciIsImlhdCI6MTc0OTg5NzQ0NiwiZXhwIjoxNzUwMDcwMjQ2fQ.Zc68XT-rZSL5JUx6hHUaUnkOfos2RIcZ_W3qZXeO6fY

###
GET http://localhost:4000/options/subjects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE1LCJlbWFpbCI6ImNoYXJhbkBueHR3YXZlLmNvLmluIiwicm9sZSI6Im1lbnRvciIsImlhdCI6MTc0OTg5NzQ0NiwiZXhwIjoxNzUwMDcwMjQ2fQ.Zc68XT-rZSL5JUx6hHUaUnkOfos2RIcZ_W3qZXeO6fY


### Submit Feedback
POST http://localhost:4000/feedback/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE1LCJlbWFpbCI6ImNoYXJhbkBueHR3YXZlLmNvLmluIiwicm9sZSI6Im1lbnRvciIsImlhdCI6MTc0OTg5NzQ0NiwiZXhwIjoxNzUwMDcwMjQ2fQ.Zc68XT-rZSL5JUx6hHUaUnkOfos2RIcZ_W3qZXeO6fY
Content-Type: application/json

{
    "section_id": 1,
    "date": "2024-03-10",
    "student_engagement": 4,
    "overall_performance": 4,
    "concern_status": "general",
    "positive_notes": "Students were actively participating in the discussion. Good understanding of concepts.",
    "suggestions": "Could include more practical examples",
    "additional_feedback": "Overall good session"
}

### Get Feedback History for a specific date
GET http://localhost:4000/feedback/history?date=2024-03-15
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE1LCJlbWFpbCI6ImNoYXJhbkBueHR3YXZlLmNvLmluIiwicm9sZSI6Im1lbnRvciIsImlhdCI6MTc0OTg5NzQ0NiwiZXhwIjoxNzUwMDcwMjQ2fQ.Zc68XT-rZSL5JUx6hHUaUnkOfos2RIcZ_W3qZXeO6fY

###
GET http://localhost:4000/feedback/history
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE1LCJlbWFpbCI6ImNoYXJhbkBueHR3YXZlLmNvLmluIiwicm9sZSI6Im1lbnRvciIsImlhdCI6MTc0OTg5NzQ0NiwiZXhwIjoxNzUwMDcwMjQ2fQ.Zc68XT-rZSL5JUx6hHUaUnkOfos2RIcZ_W3qZXeO6fY

###

GET http://localhost:4000/feedback/dates
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE1LCJlbWFpbCI6ImNoYXJhbkBueHR3YXZlLmNvLmluIiwicm9sZSI6Im1lbnRvciIsImlhdCI6MTc0OTg5NzQ0NiwiZXhwIjoxNzUwMDcwMjQ2fQ.Zc68XT-rZSL5JUx6hHUaUnkOfos2RIcZ_W3qZXeO6fY